components:
  schemas:
    CreatedEvent:
      properties:
        data:
          properties:
            id:
              type: string
          required:
          - id
          type: object
        type:
          const: Created
      required:
      - type
      - data
      type: object
    DeletedEvent:
      properties:
        data:
          properties:
            id:
              type: string
            reason:
              type: string
          required:
          - id
          - reason
          type: object
        type:
          const: Deleted
      required:
      - type
      - data
      type: object
    Event:
      discriminator:
        mapping:
          Created: '#/components/schemas/CreatedEvent'
          Deleted: '#/components/schemas/DeletedEvent'
          Restored: '#/components/schemas/RestoredEvent'
        propertyName: type
      oneOf:
      - $ref: '#/components/schemas/CreatedEvent'
      - $ref: '#/components/schemas/DeletedEvent'
      - $ref: '#/components/schemas/RestoredEvent'
    RestoredEvent:
      properties:
        data:
          properties:
            id:
              type: string
          required:
          - id
          type: object
        type:
          const: Restored
      required:
      - type
      - data
      type: object
info:
  title: Rust enum feature example
  version: 0.1.0
openapi: 3.1.0
paths: {}

